### ISSUE TITLE
Please consider detecting compiler version or bumping minimum supported Rust version

### ISSUE THREAD

**Issue by adamreichold** [Amanieu/atomic-rs#14]
A lot of the compiler features behind this crate's `nightly` feature have reached stable Rust but cannot be used when targeting it as feature flags are not allowed by the stable compiler. It would be nice if the compiler version could be detected automatically using crates like [`rustc_version`](https://crates.io/crates/rustc_version) or [`autocfg`](https://crates.io/crates/autocfg) so that the `nightly` becomes unnecessary and the relevant functionality like smaller-than-word-size atomics become available on stable Rust. (Alternatively, the minimum supported Rust version could be increased to avoid the complexity of feature detection at the cost of dropping support for older compiler versions.)

**Comment by adamreichold** [comment]
Personally, I stumbled upon this when writing generic code against `Atomic<T>` and debugging a performance issue where `Atomic<bool>` was falling back to spin locks even though the compiler supported `AtomicBool` (and `AtomicU8`).

**Comment by Amanieu** [comment]
I think at this point it's fine to just do a major version bump and increase the MSRV. Would you be willing to write up a PR for this?

**Comment by adamreichold** [comment]
> Would you be willing to write up a PR for this?

Yes, I would be glad to. But it will most likely take me until next week to prepare this.

**Comment by adamreichold** [comment]
Ah, there is one catch still: While `Atomic{U,I}{8,16,32,64}` are stable, detecting which of them is available at compile via `target_has_atomic` is not:

> Currently you'll need to use #[cfg(target_arch)] primarily to conditionally compile in code with atomics. There is an unstable #[cfg(target_has_atomic)] as well which may be stabilized in the future.

Would you prefer using `cfg(target_arch)` with a reasonable set of targets or should I do this via `autocfg` still (which will separately compile code snippets to check for the presence of types similarly to GNU `autotools`) or should I drop this for now as everything else that is stable will probably not be too helpful without the compile time configuration?

**Comment by Amanieu** [comment]
It would be great if you could get `autocfg` to work for this.

**Comment by adamreichold** [comment]
> It would be great if you could get `autocfg` to work for this.

So `autocfg` did work even though I had to probe for both the `core::` and `std::` paths as it tries to automatically detect `no_std` builds as being a property only of the target but not of the crate, i.e. my default target has a standard library and hence `autocfg` will not detect a `no_std` build even though this crate will set `![no_std]` and hence always import via `core::`.
