### ISSUE TITLE
Atomic can/should implement RefUnwindSafe

### ISSUE THREAD

**Issue by njaard** [Amanieu/atomic-rs#21]
`std` [does](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html#impl-RefUnwindSafe).

**Comment by Amanieu** [comment]
I find the whole `UnwindSafe` concept to be poorly thought out. I'll accept a PR if you need this for some reason though.

**Comment by PythonCreator27** [comment]
`Atomic` _**does**_ implement `RefUndwindSafe`, but only if the `std` feature is turned on.
