### ISSUE TITLE
Pointer types

### ISSUE THREAD

**Issue by RReverser** [Amanieu/atomic-rs#22]
The README mentions standard library's `AtomicPtr` among others, but the generic type provided by this crate doesn't seem to provide a specialisation to cover it.

Would it be possible to add implementations for `Atomic<*const T>`, `Atomic<*mut T>` and, probably, `Atomic<&'a T>`, `Atomic<&'a mut T>` and some smart pointers too?

**Comment by Amanieu** [comment]
`Atomic<*const T>` and `Atomic<*mut T>` should already work, just like any other type that is `Copy`.

**Comment by RReverser** [comment]
Ah. You're right, I only searched for `*const` / `*mut` on the long generated docs at https://amanieu.github.io/atomic-rs/atomic/struct.Atomic.html, but didn't account for a generic impl.

What do you think about adding implementations for references and standard smart pointers too?

**Comment by Amanieu** [comment]
Those would require special handling and are outside the scope of this crate. For example, consider an `Atomic<Box<T>>`. When is it safe to free the `Box` after it is swapped out? What if another thread is still accessing it. You need something like crossbeam-epoch to handle this safely.

**Comment by RReverser** [comment]
I would think those would just use `::into_raw` / `::from_raw` on `Box`, `Rc`, etc for internal conversions. With that, it's already guaranteed that if the user put a `Box` in, it was unique, and when you take one out, it can be freed immediately too. That's a good point about accessing from other threads though...

What about lifetimed references? Those should be safe to use and would behave essentially in the same way as raw pointers. In fact, due to `T: Copy` implementation, `&T` should already be accepted, so I guess it's just a matter of adding an impl for `&mut T` too?

**Comment by Amanieu** [comment]
There are aliasing issues with `&mut T` since `load` will allow you to create multiple mutable references to the same object.

**Comment by RReverser** [comment]
`load` on `&mut` could return a reference with same lifetime as `&self`, then it would be fine... But I guess it quickly gets impractical.

I think I'll try to use this crate with `&T` for now and reopen the issue if I run into those limitations.
