### ISSUE TITLE
Error in docs for compare_exchange* methods

### ISSUE THREAD

**Issue by Seeker14491** [Amanieu/atomic-rs#24]
For reference, here's all the variants of `std::atomic::Ordering`:

```rust
enum Ordering {
    Relaxed,
    Release,
    Acquire,
    AcqRel,
    SeqCst,
}
```

This crate's [docs for `compare_exchange()` and `compare_exchange_weak()`](https://docs.rs/atomic/0.5.0/atomic/struct.Atomic.html#method.compare_exchange) state

> The failure ordering can't be Acquire or AcqRel . . .

This suggests the valid options are Relaxed, Release, or SeqCst. However, [the docs for `compare_exchange()` in the standard library](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicBool.html#method.compare_exchange) state

> The failure ordering can only be SeqCst, Acquire or Relaxed . . .

There is a mismatch with Acquire and Release, which I assume is not correct.

**Comment by Amanieu** [comment]
Oops, the standard library is correct here. The failure ordering can only acquire, not release.
