### ISSUE TITLE
Why compare `align_of`?

### ISSUE THREAD

**Issue by rise0chen** [Amanieu/atomic-rs#25]
``` rust
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Test {
    a: u8,
    b: u8,
    c: u8,
    d: u8,
}
fn main() {
    println!("align: {}", core::mem::align_of::<Test>());
    println!("size: {}", core::mem::size_of::<Test>());
}
```
Size of the struct is `4`, align of  the struct is `1`.
The condition is not met.
![image](https://user-images.githubusercontent.com/12853908/149717002-c6ccf009-d98d-4eeb-91b1-58356e976f59.png)

**Comment by rise0chen** [comment]
I think `Atomic<Test >` can be converted to `AtomicU32`

**Comment by Amanieu** [comment]
You can use `#[repr(align(4))]` on your struct to ensure the alignment is sufficient. This is required since this crate will unsafely access your struct as an `AtomicU32`.

**Comment by rise0chen** [comment]
![image](https://user-images.githubusercontent.com/12853908/149744504-fceca354-5647-4d33-9a47-c72e8a54d557.png)
`transmute` don't require alignment, how about replace `transmute_copy` by `transmute`?

**Comment by Amanieu** [comment]
This crate isn't actually transmuting though, it's casting a pointer to your type to a pointer to `AtomicU32` and accessing it as an `AtomicU32` in-place. This requires that your type be suitably aligned for an `AtomicU32`.
