### ISSUE TITLE
Enum can't work as expected.

### ISSUE THREAD

**Issue by rise0chen** [Amanieu/atomic-rs#26]
```rust
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
 #[repr(align(2))]
pub enum Test {
    A,
    B(u8),
}
```
`Test::A` maybe is 0x0000 or 0xXX00, so it maybe not equal when transmute to u16.

**Comment by Amanieu** [comment]
You're right, enums will not work with this crate. Only types which have no paddings bytes and no invalid values will work. This effectively constraints it to structs with no padding bytes.

**Comment by rise0chen** [comment]
```rust
#[repr(align(4))]
pub struct Test {
    a: u8,
    b: u16,
}
```
Does this struct have paddings bytes?

**Comment by Amanieu** [comment]
Yes it does.
