### ISSUE TITLE
Test failure on little endian architectures

### ISSUE THREAD

**Issue by werdahias** [Amanieu/atomic-rs#30]
I am the maintainer for rust-atomic on debian. The crate builds on little-endian architectures ( armel, mipsel and mips64el). The tests fail though. I attached the log below. Note the assertion failure. This is because of the way little-endian encodes bits, see this debian wiki [entry](https://wiki.debian.org/ArchitectureSpecificsMemo).  I'd appriciate if you'd take some time to look at that as it blocks the testing migration. 
Thanks
[log.txt](https://github.com/Amanieu/atomic-rs/files/9050285/log.txt)

**Comment by plugwash** [comment]
Nothing to do with endian. It passes on i386 (little endian), amd64 (little endian), arm64 (little endian), armhf (little endian) i386 (little endian), s390x (little endian) and riscv64 (little endian)  while failing on armel (little endian) mipsel (little endian), mips64el (little endian) powerpc (big endian) and ppc64 (big endian).

I belie this is a bug in the compiler and/or standard library, I filed it at https://github.com/rust-lang/rust/issues/100650#issuecomment-1217501037
