### ISSUE TITLE
Test failure on amd64 because fallback is disabled by default

### ISSUE THREAD

**Issue by werdahias** [Amanieu/atomic-rs#31]
I am the maintainer for rust-atomic on debian. The crate builds on amd64. The tests fail though because the fallback feature is disabled by default. I attached the log below. Please consider enabling this feature by default so the tests pass. Log:
[log.txt](https://github.com/Amanieu/atomic-rs/files/9050320/log.txt)

**Comment by Amanieu** [comment]
The `fallback` feature is enabled by default.

**Comment by CountOmega** [comment]
I maybe missed the point a bit. When running the unit tests, the default feature doesn't seem to be enable, so the test fail.

**Comment by plugwash** [comment]
The feature is enabled by default, Debian's standard CI setup tests a number of configurations including all features disabled, each feature enabled individually, default features enabled and all features enabled.

I'm working on a patch to make the tests pass when all features are disabled, but there are some subtleties around what is supported on what architectures.

**Comment by plugwash** [comment]
Patch to make tests pass with --no-default-features can be found at https://salsa.debian.org/rust-team/debcargo-conf/-/blob/5ece2ac37ec3e7ea2174be016e7f852ee3767b95/src/atomic/debian/patches/fix-tests-no-default-features.patch
