### ISSUE TITLE
calling an Atomic<fn()> is UB according to Miri:

### ISSUE THREAD

**Issue by oconnor663** [Amanieu/atomic-rs#35]
When I put a function pointer in an `Atomic<fn(...)>`, retrieve it, and call it, everything appears to work fine both in debug mode and under `--release`. (Incidentally I'm thrilled that this works in safe, `no_std` code. Thank you!) However, Miri seems confused about something. Here's an example of a trivial program that triggers a Miri error. This is reproducible on the playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8837375426cd12de633d73dbfbc25dc3

```rust
use atomic::{Atomic, Ordering};

fn my_noop_fn() {}

static NOOP_FN: Atomic<fn()> = Atomic::new(my_noop_fn);

fn main() {
    let f = NOOP_FN.load(Ordering::SeqCst);
    f();
}
```

```
$ cargo +nightly miri run
error: Undefined Behavior: out-of-bounds pointer use: 0x26b44[noalloc] is a dangling pointer (it has no provenance)
 --> src/main.rs:9:5
  |
9 |     f();
  |     ^^^ out-of-bounds pointer use: 0x26b44[noalloc] is a dangling pointer (it has no provenance)
  |
```

I don't have any ideas about what exactly is going wrong here. Have you seen this before?

**Comment by taiki-e** [comment]
This is due to ptr-to-int-to-ptr cast losses the provenance. https://github.com/rust-lang/miri/issues/2926

It can be reproduced using AtomicUsize and can be avoided using AtomicPtr: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5c35262cc2aa064c28d77ad57d04d2aa)
